```{r setup, echo=FALSE, message=FALSE}
## Uncomment after your are ready to publish the post
#opts_knit$set(upload.fun=imgur_upload)
opts_chunk$set(fig.width=5, fig.height=5, cache=TRUE)

## Load knitcitations with a clean bibliography
library(knitcitations)
cleanbib()
cite_options(tooltip=TRUE)

## I made my own citing function since citep() doesn't work like I want to with
## urls that are not really pages themselve like part of a GitHub repo.
mycitep <- function(x, short, year=substr(date(), 21, 24), tooltip=TRUE) {
	tmp <- citep(x)
	res <- gsub("></a>", paste0(">", short, "</a>"), tmp)
	if(tooltip) {
		res <- gsub("\\?\\?\\?\\?", year, res)
	}
	res
}
## Here's an example
# mycitep("https://github.com/lcolladotor/lcollado753", "Collado, 2013")
```
```{r bibsetup, echo=FALSE, message=FALSE, warning=FALSE}
write.bibtex(c("knitcitations" = citation("knitcitations", "plyr"=citation("plyr"), "doMC"=citation("doMC"))), file = "pkgs.bib")
bib <- read.bibtex("pkgs.bib")
```



Start post


Citations made with `knitcitations` `r mycitep(bib[["knitcitations"]], "Boettiger, 2013")`.


```{r results='asis', echo=FALSE, cache=FALSE}
## Print bibliography
bibliography()
```
